title: "Lane Widen"
description: "A Permutation of Daniel Wen"
url: "https://lane-widen.com"
permalink: /:title/

markdown: kramdown
kramdown:
    math_engine: ritex
sass:
    style: :nested
    #style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
 - jekyll-coffeescript